version: "3"
services:
  hub:
    image: selenium/hub:3.14
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:3.14
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:3.14
    shm_size: 1gb
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  testng:
    image: gnana3/seleniumtest
    depends_on: 
      - chrome
      - firefox
    environment:
      - BROWSER=firefox
      - HUB_HOST=hub
      - MODULE=testng.xml
    volumes:
        - ./results-output:/usr/share/project/test-output
        - ./extent-reports:/usr/share/project/ExtentReports